import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "./components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen flex items-center justify-center p-4">
          <div className="w-full h-full flex items-center justify-center border border-gray-400">
            <Sidebar />
            <div className="relative w-fit h-full flex flex-1 items-center justify-center overflow-y-scroll">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
